### ISSUE TITLE
A Critique of Resizable Hash Tables: Riak Core & Random Slicing

### ISSUE THREAD

**Issue by ordepdev** [talkdesk-sandbox/data-tech-talks#2]
The article https://www.infoq.com/articles/dynamo-riak-random-slicing gives us a very decent amount of food for thought on hash tables, cluster placements, and blah blah blah.

**Comment by luisfmcalado** [comment]
Presentation slides: [here](https://github.com/talkdesk-sandbox/data-tech-talks/files/2511050/slide-desk.pdf).
